apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: hc-test-downstream-run-
spec:
  pipelineRef:
    name: test-hc-on-claimed-cluster
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi