apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: alertmanager-to-github-secrets
  namespace: alertmanager-to-github
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: alertmanager-to-github-secret-gen
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: alertmanager-to-github
                  namespace: alertmanager-to-github
                type: Opaque
                stringData:
                  ATG_GITHUB_TOKEN: '{{fromSecret "open-cluster-management" "kcp-sgs-pipelines-secrets-config" "githubToken" | base64dec }}'
        remediationAction: inform
        severity: low
  remediationAction: enforce
