apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: notify-status-upgrade
spec:
  params:
  - name: snapshot
    default: ""
    description: The SNAPSHOT Tag used to deploy the catalogsources
    type: string 
  - name: targetSnapshot
    default: ""
    description: The SNAPSHOT Tag used to deploy the catalogsources
    type: string 
  - name: runStatus
    default: ""
    description: Overall status of the pipeline run
    type: string     
  - name: hubOcLogin
    default: ""
    description: OC Login command for the Hub cluster
    type: string 
  - name: spokeOcLogin
    default: ""
    description: OC Login command for the Spoke cluster
    type: string         
  - name: sendNotification
    default: "false"
    description: Sends notification to slack if value is true
    type: string       
  steps:
  - args:
    - |-
      #!/bin/bash
      set -e

      if [[ "$(inputs.params.sendNotification)" == "true" ]]; then
        echo "Send notification to acm-hypershift-notifications slack channel"
        curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"HyperShift test with ACM upgrade\n  ACM 2.6 build: $(inputs.params.snapshot)\n  ACM 2.7 build: $(inputs.params.targetSnapshot)\nOverall status: $(inputs.params.runStatus)\"}" https://hooks.slack.com/services/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
      else
        echo "Skip notification to slack channel"
      fi

      exit 0

    command:
    - /bin/bash
    - -c
    image: quay.io/zkayyali812/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source
