apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-hc-after-upgrade
spec:
  params:
  - name: clusterClaimName
    default: demo-claim
    description: The name of the clusterclaim to use
    type: string
  - name: targetManagedCluster
    default: local-cluster
    description: The managedcluster to target to become a managementcluster
    type: string
  steps:
  - args:
    - |-
      #!/bin/bash
      
      _LOGIN_CMD=$(cat login.sh)
      eval "$_LOGIN_CMD"
      
      echo "Cleaning up hosted cluster after upgrade clusters/$(inputs.params.targetManagedCluster)-hd"
      oc project

      INFRAID=$(oc get hypershiftdeployments -n $(inputs.params.targetManagedCluster) $(inputs.params.targetManagedCluster)-hd -oyaml| yq eval '.spec.hostedClusterSpec.infraID' - )
      AWS_CREDS_FILE=~/.aws/credentials

      # The AWS creds
      AWS_ACCESS_KEY_ID=$(oc get secret acm-credentials -n $(inputs.params.targetManagedCluster) -o yaml | yq eval '.data.aws_access_key_id' - | base64 -d)
      AWS_SECRET_ACCESS_KEY=$(oc get secret acm-credentials -n $(inputs.params.targetManagedCluster) -o yaml | yq eval '.data.aws_secret_access_key' - | base64 -d)
      # Create AWS credentials file
      mkdir ~/.aws

      cat <<EOF >~/.aws/credentials
      [default]
      aws_access_key_id=${AWS_ACCESS_KEY_ID}
      aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}
      EOF

      oc get hc -n clusters $(inputs.params.targetManagedCluster)-hd
      if [ $? -eq 0 ]; then
          set -e

          echo "Delete hosted cluster clusters/$(inputs.params.targetManagedCluster)-hd"
          oc delete hc -n clusters $(inputs.params.targetManagedCluster)-hd

          echo "Delete manifestwork $(inputs.params.targetManagedCluster)/$INFRAID"
          oc delete manifestwork -n $(inputs.params.targetManagedCluster) $INFRAID

          echo "Destroy AWS resources infraID: $INFRAID"
          hypershift destroy infra aws --infra-id $INFRAID --aws-creds $AWS_CREDS_FILE --base-domain dev06.red-chesterfield.com  --region=us-east-2

          hypershift destroy iam aws --infra-id $INFRAID --aws-creds $AWS_CREDS_FILE --region=us-east-2

          echo "Hosted cluster successfully deleted"
      fi

      exit 0

    command:
    - /bin/bash
    - -c
    image: quay.io/phwu/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source
