apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
 name: hs-ci-ds-upgrade-github-listener
spec:
 serviceAccountName: pipeline
 triggers:
   - bindings:
       - ref: hs-ci-pipeline-binding
     template:
       ref: hs-ci-ds-upgrade-trigger-pipeline-template
