apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-ensure-hd-console-disabled
  namespace: policies
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/controls: SC-28 Protection Of Information At Rest
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: disable-hd-console
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.openshift.io/v1
                kind: Console
                metadata:
                  name: cluster
                spec:
                  logLevel: Normal
                  managementState: Removed
                  operatorLogLevel: Normal
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: ensure-hd-console-disabled
        spec:
          remediationAction: inform
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.openshift.io/v1
                kind: Console
                metadata:
                  name: cluster
                spec:
                  logLevel: Normal
                  managementState: Removed
                  operatorLogLevel: Normal
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-ensure-hd-console-disabled
  namespace: policies
placementRef:
  name: placement-policy-ensure-hd-console-disabled
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-ensure-hd-console-disabled
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-ensure-hd-console-disabled
  namespace: policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: "cluster.open-cluster-management.io/clusterset", operator: In, values: ["kcp-stable-redhat-acm-compute", "kcp-unstable-redhat-acm-compute"]}
      - {key: "vendor", operator: In, values: ["OpenShift"]}
